site_name: DENOG Routing Guide
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  font: false
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: 'yellow'
      accent: 'yellow'
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: 'yellow'
      accent: 'yellow'
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
copyright: Copyright &copy; DENOG e.V. <br/><a href="https://www.denog.de/de/impressum.html">Imprint</a>
markdown_extensions:
  #- pymdownx.emoji
    #emoji_index: !!python/name:material.extensions.emoji.twemoji
        #emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
plugins:
  - git-revision-date-localized
extra:
  status:
    <identifier>: <description>
