site_name: DENOG Routing Guide
repo_url: https://github.com/denog/routing-guide
edit_uri: edit/main/docs/
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  font: false
  features:
    - content.action.edit
    - content.action.view
  icon:
    edit: material/pencil
    view: material/eye
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: 'yellow'
      accent: 'yellow'
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: 'yellow'
      accent: 'yellow'
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
copyright: Copyright &copy; DENOG e.V. <br/><a href="https://www.denog.de/de/impressum.html">Imprint</a>
