name: Lint
on:
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: read

jobs:
  editorconfig:
    name: Editorconfig
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: editorconfig-checker/action-editorconfig-checker@v2
      - run: editorconfig-checker
